### ISSUE TITLE
Higher Resolution Problems

### ISSUE THREAD

**Issue by 10000turtles** [casey-c/spiretool-infomod#1]
Hey,

I happen to have a pretty big monitor that has a very wide setting. Because of this, I can't play in full-screen without the extra stats going off the page. As well, I cant move the potions percentage up to the top bar because it only goes to a max of 1080. I know its SUPER DUPER not necessary for 99% of users but if it was fixed (possibly by adding functionality to customize max x and y coordinates) that would be very cool. Thanks :D

**Comment by casey-c** [comment]
I appreciate the feedback a ton, thank you! This is something I was originally worried about while implementing since I didn't have a decent way to test it on my own, and I'm sorry to hear that it happened. 

I think some of my code tries to let the UI scale up to the current resolution, but a whole lot of it doesn't (mostly due to me not being sure if the "fix" I was doing was actually doing anything at all). Currently the approach I've been trying to do is to compute everything at 1920x1080 and then scale up using a scaling factor provided by the base game (this scaling factor is required to be set at every render call, and I've been super lazy in omitting it). I am also a bit worried that the scaling factor as is won't handle super wide resolutions. I will have to look into the base game code a bit more and investigate how they do it correctly :)

If you'd be willing to assist in providing some screenshots so I can try and see what's happening - it would be super helpful for me to debug.

Can you provide screenshots of the following screens (you can use the steam screenshot functionality with F12 and then comment a reply with the links, or use any other method like uploading to imgur or something):

* Config menu (MainMenu->Mods->InfoMod->Config)
* Monster compendium (shift right click a monster) - [I'm assuming the shift right click monster works at least - hopefully the ultra wide doesn't affect the hitboxes]
* In game potion tracker settings (click the [?] box)


In theory these should all be centered, nice looking, and readable, but I imagine they end up looking really incorrect, and I'd like to see exactly how wrong they turned out. (And hopefully spot the places where I've implemented the "fix" and see if it did anything)

I will work towards getting out a temporary workaround with the menu option going to screen resolution instead of a hardcoded 1920x1080, to hopefully get that piece working for you :)

**Comment by casey-c** [comment]
Followup: did some more diving into the source code to see if I could find out how the devs handle ultrawide resolutions. It seems like the "fix" I have in mind should theoretically work. I've been working on a very large scale rewrite of the whole rendering process and will apply it there, and hopefully you won't have any more issues. Those updates should *hopefully* trickle back down into InfoMod in the next 2-4 weeks (it's been a pretty huge undertaking).

I'm still curious to see what it looks like currently (My guess would be absolutely unreadable and unusable, but I don't know for sure - I might be surprised). It would also help me narrow down a bit where I need to apply the fixes :)

**Comment by 10000turtles** [comment]
---------- Forwarded message ---------
From: Justin Mucelli <10000turtles@gmail.com>
Date: Sun, Sep 13, 2020 at 10:50 PM
Subject: Re: Delivery Status Notification (Failure)
To: Mail Delivery Subsystem <mailer-daemon@googlemail.com>


Okay so that didn't work... Here's a google drive link instead. Sorry!

Link:
https://drive.google.com/drive/folders/1KyCd2iwXiOrzIzOc51wsTvtjY6Fh18si?usp=sharing

**Comment by casey-c** [comment]
Hey - thanks for the screenshots. I've released a tiny update [0.5.8](https://github.com/casey-c/spiretool-infomod/releases/tag/0.5.8) as a first attempt to fix this issue. Again, I couldn't test it against a high resolution monitor so I'll need your assistance there. Please take a look around at it and let me know what you see (what's working/what's broken/etc.)!

**Comment by casey-c** [comment]
@10000turtles 

Hi - can you confirm if the [0.5.8 release](https://github.com/casey-c/spiretool-infomod/releases/tag/0.5.8) fixes any of the issues you encountered? I would like to know if those attempts succeeded so I can proceed in that direction / try a new one if needed. Thanks!

**Comment by kordra** [comment]
I can confirm that the menu issues seem fixed but when you hover over the ? it still showing half the dialog off screen at 1440p.

**Comment by casey-c** [comment]
Thanks for the feedback! I definitely forgot to apply the fix to the tool tip boxes (which is a bit sad given that the majority of info mod takes place in tool tips haha - it's a pretty big oops). I will try and push a patch sometime this upcoming week to hopefully get it fixed.

I apologize for the late response / lack of updates - been a bit busy with real life stuff!
